---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: focalboard
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/focalboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: focalboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: focalboard